trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployAppointment
    jobs:
      - job: Deploy
        steps:
          - template: ../templates/dotnet-deploy-template.yml
            parameters:
              appName: 'AppointmentServiceApp'
              projectPath: 'services/AppointmentService/AppointmentService.API/AppointmentService.API.csproj'
