name: Deploy-AppointmentService

extends:
  template: ../../templates/dotnet-deploy-template.yml
  parameters:
    appName: 'hqms-doctor-api'
    projectPath: 'services\AppointmentService\AppointmentService.API\AppointmentService.API.csproj'
