name: Deploy-AuthService

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/AuthService/**

variables:
- group: HQMS-Shared

stages:
# Build
- stage: Build
  displayName: "Build & Publish Auth Service"
  jobs:
    - job: BuildJob
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-auth-api'
            projectPath: 'services/AuthService/AuthService.API/AuthService.API.csproj'
            buildOnly: true
            resourceGroupName: $(resourceGroupName)

# Deploy Staging
- stage: Deploy_Staging
  displayName: "Deploy Auth Service to Staging"
  dependsOn: Build
  jobs:
    - deployment: StagingDeploy
      environment: 'Staging'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ../../templates/dotnet-deploy-template.yml
                parameters:
                  appName: 'hqms-auth-api-staging'
                  projectPath: 'services/AuthService/AuthService.API/AuthService.API.csproj'
                  buildOnly: false
                  resourceGroupName: $(resourceGroupName)

# Deploy Production
- stage: Deploy_Prod
  displayName: "Deploy Auth Service to Production"
  dependsOn: Deploy_Staging
  condition: succeeded()
  jobs:
    - deployment: ProdDeploy
      environment: 'Prod'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ../../templates/dotnet-deploy-template.yml
                parameters:
                  appName: 'hqms-auth-api'
                  projectPath: 'services/AuthService/AuthService.API/AuthService.API.csproj'
                  buildOnly: false
                  resourceGroupName: $(resourceGroupName)
