name: Deploy-AuthService

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/AuthService/**

variables:
- group: HQMS-Shared

stages:
- stage: Build
  displayName: "Build & Publish Auth Service"
  jobs:
    - job: BuildJob
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-auth-api'
            projectPath: 'services/AuthService/AuthService.API/AuthService.API.csproj'
            buildOnly: true
            resourceGroupName: $(resourceGroupName)

- stage: Deploy_Staging
  displayName: "Deploy Auth Service to Staging"
  dependsOn: Build
  jobs:
    - job: StagingDeploy
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-auth-api-staging'
            projectPath: 'services/AuthService/AuthService.API/AuthService.API.csproj'
            buildOnly: false
            resourceGroupName: $(resourceGroupName)

- stage: Deploy_Prod
  displayName: "Deploy Auth Service to Production"
  dependsOn: Deploy_Staging
  condition: succeeded()
  jobs:
    - job: ProdDeploy
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-auth-api'
            projectPath: 'services/AuthService/AuthService.API/AuthService.API.csproj'
            buildOnly: false
            resourceGroupName: $(resourceGroupName)
