name: Deploy-AuthService

extends:
  template: ../../templates/dotnet-deploy-template.yml
  parameters:
    appName: 'hqms-auth-api'
    projectPath: 'services\AuthService\AuthService.API\AuthService.API.csproj'
