name: Deploy-QueueService

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/QueueService/**

variables:
- group: HQMS-Shared

stages:
# Build Stage
- stage: Build
  displayName: "Build & Publish Queue Service"
  jobs:
    - job: BuildJob
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-queue-api'
            projectPath: 'services/QueueService/QueueService.API/QueueService.API.csproj'
            buildOnly: true
            resourceGroupName: $(resourceGroupName)

# Deploy to Staging
- stage: Deploy_Staging
  displayName: "Deploy Queue Service to Staging"
  dependsOn: Build
  jobs:
    - deployment: StagingDeploy
      environment: 'Staging'
      strategy:
        runOnce:
          deploy:
            steps:
              - template: ../../templates/dotnet-deploy-template.yml
                parameters:
                  appName: 'hqms-queue-api-staging'
                  projectPath: 'services/QueueService/QueueService.API/QueueService.API.csproj'
                  buildOnly: false
                  resourceGroupName: $(resourceGroupName)

# Deploy to Production
- stage: Deploy_Prod
  displayName: "Deploy Queue Service to Production"
  dependsOn: Deploy_Staging
  condition: succeeded()
  jobs:
    - deployment: ProdDeploy
      environment: 'Prod'
      strategy:
        runOnce:
          preDeploy:
            steps:
              - task: AzureWebApp@1
                displayName: "Deploy to Staging Slot"
                inputs:
                  azureSubscription: $(azureSubscription)
                  appType: 'webApp'
                  appName: 'hqms-queue-api'
                  deployToSlotOrASE: true
                  resourceGroupName: $(resourceGroupName)
                  slotName: 'staging'
                  package: '$(Pipeline.Workspace)/drop/**/*.zip'
          routeTraffic:
            steps:
              - task: AzureAppServiceManage@0
                displayName: "Swap Staging Slot with Production"
                inputs:
                  azureSubscription: $(azureSubscription)
                  Action: 'Swap Slots'
                  WebAppName: 'hqms-queue-api'
                  ResourceGroupName: $(resourceGroupName)
                  SourceSlot: 'staging'
                  SwapWithProduction: true
          on:
            failure:
              steps:
                - task: AzureAppServiceManage@0
                  displayName: "Rollback to Previous Production"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    Action: 'Swap Slots'
                    WebAppName: 'hqms-queue-api'
                    ResourceGroupName: $(resourceGroupName)
                    SourceSlot: 'staging'
                    TargetSlot: 'production'
