name: Deploy-NotificationService

extends:
  template: ../templates/dotnet-deploy-template.yml
  parameters:
    appName: 'hqms-notification-api'
    projectPath: '../Services/NotificationService/NotificationService.csproj'
