name: Deploy-NotificationService

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/NotificationService/**

variables:
- group: HQMS-Shared

stages:
- stage: Build
  displayName: "Build & Publish Notification Service"
  jobs:
    - job: BuildJob
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-notification-api'
            projectPath: 'services/NotificationService/NotificationService.API/NotificationService.API.csproj'
            buildOnly: true
            resourceGroupName: $(resourceGroupName)

- stage: Deploy_Staging
  displayName: "Deploy Notification Service to Staging"
  dependsOn: Build
  jobs:
    - job: StagingDeploy
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-notification-api-staging'
            projectPath: 'services/NotificationService/NotificationService.API/NotificationService.API.csproj'
            buildOnly: false
            resourceGroupName: $(resourceGroupName)

- stage: Deploy_Prod
  displayName: "Deploy Notification Service to Production"
  dependsOn: Deploy_Staging
  condition: succeeded()
  jobs:
    - job: ProdDeploy
      pool:
        vmImage: 'windows-latest'
      steps:
        - template: ../../templates/dotnet-deploy-template.yml
          parameters:
            appName: 'hqms-notification-api'
            projectPath: 'services/NotificationService/NotificationService.API/NotificationService.API.csproj'
            buildOnly: false
            resourceGroupName: $(resourceGroupName)
