name: Deploy-NotificationService

extends:
  template: ../templates/dotnet-deploy-template.yml
  parameters:
    appName: 'hqms-notification-api'
    projectPath: 'src/Services/NotificationService/NotificationService.csproj'
