trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployNotification
    jobs:
      - job: Deploy
        steps:
          - template: ../../templates/dotnet-deploy-template.yml
            parameters:
              appName: 'NotificationServiceApp'
              projectPath: 'services/NotificationService/NotificationService.API/NotificationService.API.csproj'
