trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployNotification
    displayName: "Deploy Notification Service"
    jobs:
      - job: Deploy
        displayName: "Build & Deploy Notification Service"
        steps:
          - template: ../../templates/dotnet-deploy-template.yml
            parameters:
              appName: 'hqms-notification-api'
              projectPath: 'services/NotificationService/NotificationService.API/NotificationService.API.csproj'
